name: data_class_macro
description: Experimental support for data classes in Dart using pkg:macros
version: 0.0.0-dev.6
repository: https://github.com/felangel/data_class
topics: [macros, data-class]

environment:
  sdk: ^3.5.0-152.0.dev

dependencies:
  collection: ^1.0.0
  macros: ^0.1.0-main.5

dev_dependencies:
  test: ^1.0.0
